# Generated by Django 2.1.7 on 2019-02-28 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_count', models.IntegerField(default=1)),
                ('duration', models.CharField(choices=[('30', '30 Min'), ('60', '1 Hour'), ('120', '2 Hours')], max_length=3)),
                ('ride_date', models.DateTimeField()),
                ('horse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.Horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
